# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 803)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_password = QtWidgets.QLabel(self.tab)
        self.lab_password.setObjectName("lab_password")
        self.gridLayout.addWidget(self.lab_password, 0, 4, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(self.tab)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 0, 7, 1, 1)
        self.lab_password_2 = QtWidgets.QLabel(self.tab)
        self.lab_password_2.setObjectName("lab_password_2")
        self.gridLayout.addWidget(self.lab_password_2, 2, 4, 1, 1)
        self.filePath = QtWidgets.QLineEdit(self.tab)
        self.filePath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 2, 5, 1, 1)
        self.lab_user = QtWidgets.QLabel(self.tab)
        self.lab_user.setObjectName("lab_user")
        self.gridLayout.addWidget(self.lab_user, 0, 2, 1, 1)
        self.textEdit_database = QtWidgets.QTextEdit(self.tab)
        self.textEdit_database.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_database.sizePolicy().hasHeightForWidth())
        self.textEdit_database.setSizePolicy(sizePolicy)
        self.textEdit_database.setMinimumSize(QtCore.QSize(256, 417))
        self.textEdit_database.setReadOnly(True)
        self.textEdit_database.setObjectName("textEdit_database")
        self.gridLayout.addWidget(self.textEdit_database, 6, 9, 1, 1)
        self.password = QtWidgets.QLineEdit(self.tab)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 0, 5, 1, 1)
        self.table_data = QtWidgets.QTableWidget(self.tab)
        self.table_data.setRowCount(50)
        self.table_data.setColumnCount(8)
        self.table_data.setObjectName("table_data")
        self.gridLayout.addWidget(self.table_data, 6, 0, 1, 9)
        self.btn_login = QtWidgets.QPushButton(self.tab)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 0, 6, 1, 1)
        self.lab_database = QtWidgets.QLabel(self.tab)
        self.lab_database.setObjectName("lab_database")
        self.gridLayout.addWidget(self.lab_database, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 2)
        self.cbb_database = QtWidgets.QComboBox(self.tab)
        self.cbb_database.setObjectName("cbb_database")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.gridLayout.addWidget(self.cbb_database, 2, 3, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.tab)
        self.userName.setClearButtonEnabled(True)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 0, 3, 1, 1)
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_search.setClearButtonEnabled(True)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout.addWidget(self.lineEdit_search, 3, 2, 1, 4)
        self.btn_execute = QtWidgets.QPushButton(self.tab)
        self.btn_execute.setObjectName("btn_execute")
        self.gridLayout.addWidget(self.btn_execute, 3, 6, 1, 1)
        self.btn_open = QtWidgets.QPushButton(self.tab)
        self.btn_open.setObjectName("btn_open")
        self.gridLayout.addWidget(self.btn_open, 2, 6, 1, 1)
        self.btn_upload = QtWidgets.QPushButton(self.tab)
        self.btn_upload.setObjectName("btn_upload")
        self.gridLayout.addWidget(self.btn_upload, 2, 7, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_trainProcess = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_trainProcess.sizePolicy().hasHeightForWidth())
        self.frame_trainProcess.setSizePolicy(sizePolicy)
        self.frame_trainProcess.setStyleSheet("background-color: rgb(201, 201, 201);\n"
"border-radius: 5px;")
        self.frame_trainProcess.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_trainProcess.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_trainProcess.setLineWidth(3)
        self.frame_trainProcess.setMidLineWidth(3)
        self.frame_trainProcess.setObjectName("frame_trainProcess")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_trainProcess)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_plot_2 = QtWidgets.QWidget(self.frame_trainProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_2.sizePolicy().hasHeightForWidth())
        self.widget_plot_2.setSizePolicy(sizePolicy)
        self.widget_plot_2.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.gridLayout_5.addWidget(self.widget_plot_2, 1, 1, 1, 1)
        self.widget_plot_1 = QtWidgets.QWidget(self.frame_trainProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_1.sizePolicy().hasHeightForWidth())
        self.widget_plot_1.setSizePolicy(sizePolicy)
        self.widget_plot_1.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.gridLayout_5.addWidget(self.widget_plot_1, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lcd_epoch = QtWidgets.QLCDNumber(self.frame_trainProcess)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_epoch.setFont(font)
        self.lcd_epoch.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(65,65,65);\n"
"")
        self.lcd_epoch.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_epoch.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcd_epoch.setLineWidth(2)
        self.lcd_epoch.setMidLineWidth(0)
        self.lcd_epoch.setDigitCount(6)
        self.lcd_epoch.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_epoch.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_epoch.setProperty("value", 0.0)
        self.lcd_epoch.setProperty("intValue", 0)
        self.lcd_epoch.setObjectName("lcd_epoch")
        self.gridLayout_9.addWidget(self.lcd_epoch, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 2, 1, 1)
        self.lab_Epoch = QtWidgets.QLabel(self.frame_trainProcess)
        self.lab_Epoch.setStyleSheet("color: rgb(15, 15, 15);\n"
"background-color: rgb(201, 201, 200);\n"
"font: 100 10pt \"微软雅黑\";\n"
"")
        self.lab_Epoch.setObjectName("lab_Epoch")
        self.gridLayout_9.addWidget(self.lab_Epoch, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_trainProcess, 0, 1, 1, 1)
        self.textEdit_trainResult = QtWidgets.QTextEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_trainResult.sizePolicy().hasHeightForWidth())
        self.textEdit_trainResult.setSizePolicy(sizePolicy)
        self.textEdit_trainResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_trainResult.setStyleSheet("border-radius:5px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(240, 240, 240);\n"
"background-color: rgb(201, 201, 201);\n"
"")
        self.textEdit_trainResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_trainResult.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_trainResult.setLineWidth(3)
        self.textEdit_trainResult.setMidLineWidth(3)
        self.textEdit_trainResult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_trainResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_trainResult.setObjectName("textEdit_trainResult")
        self.gridLayout_2.addWidget(self.textEdit_trainResult, 1, 1, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(210, 480))
        self.toolBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.toolBox.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.BP = QtWidgets.QWidget()
        self.BP.setGeometry(QtCore.QRect(0, 0, 197, 587))
        self.BP.setObjectName("BP")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.BP)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btn_startTrain = QtWidgets.QPushButton(self.BP)
        self.btn_startTrain.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_startTrain.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_startTrain.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-play-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_startTrain.setIcon(icon)
        self.btn_startTrain.setIconSize(QtCore.QSize(35, 35))
        self.btn_startTrain.setAutoDefault(False)
        self.btn_startTrain.setDefault(False)
        self.btn_startTrain.setFlat(True)
        self.btn_startTrain.setObjectName("btn_startTrain")
        self.gridLayout_11.addWidget(self.btn_startTrain, 26, 1, 1, 1)
        self.lab_input = QtWidgets.QLabel(self.BP)
        self.lab_input.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_input.setObjectName("lab_input")
        self.gridLayout_11.addWidget(self.lab_input, 5, 0, 1, 1)
        self.btn_suspend = QtWidgets.QPushButton(self.BP)
        self.btn_suspend.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_suspend.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_suspend.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-stop-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_suspend.setIcon(icon1)
        self.btn_suspend.setIconSize(QtCore.QSize(35, 35))
        self.btn_suspend.setAutoDefault(False)
        self.btn_suspend.setDefault(False)
        self.btn_suspend.setFlat(True)
        self.btn_suspend.setObjectName("btn_suspend")
        self.gridLayout_11.addWidget(self.btn_suspend, 26, 0, 1, 1)
        self.checkBox_saveImg = QtWidgets.QCheckBox(self.BP)
        self.checkBox_saveImg.setMinimumSize(QtCore.QSize(70, 23))
        self.checkBox_saveImg.setMaximumSize(QtCore.QSize(70, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_saveImg.setFont(font)
        self.checkBox_saveImg.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 8pt \"微软雅黑\";")
        self.checkBox_saveImg.setChecked(False)
        self.checkBox_saveImg.setObjectName("checkBox_saveImg")
        self.gridLayout_11.addWidget(self.checkBox_saveImg, 25, 1, 1, 1)
        self.checkBox_saveModel = QtWidgets.QCheckBox(self.BP)
        self.checkBox_saveModel.setEnabled(True)
        self.checkBox_saveModel.setMinimumSize(QtCore.QSize(70, 23))
        self.checkBox_saveModel.setMaximumSize(QtCore.QSize(70, 23))
        self.checkBox_saveModel.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 8pt \"微软雅黑\";")
        self.checkBox_saveModel.setChecked(False)
        self.checkBox_saveModel.setObjectName("checkBox_saveModel")
        self.gridLayout_11.addWidget(self.checkBox_saveModel, 25, 0, 1, 1)
        self.dsb_testRate = QtWidgets.QDoubleSpinBox(self.BP)
        self.dsb_testRate.setFrame(True)
        self.dsb_testRate.setDecimals(1)
        self.dsb_testRate.setMinimum(0.1)
        self.dsb_testRate.setMaximum(1.0)
        self.dsb_testRate.setSingleStep(0.1)
        self.dsb_testRate.setProperty("value", 0.1)
        self.dsb_testRate.setObjectName("dsb_testRate")
        self.gridLayout_11.addWidget(self.dsb_testRate, 24, 1, 1, 1)
        self.lab_dropout_2 = QtWidgets.QLabel(self.BP)
        self.lab_dropout_2.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_dropout_2.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_dropout_2.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_dropout_2.setObjectName("lab_dropout_2")
        self.gridLayout_11.addWidget(self.lab_dropout_2, 24, 0, 1, 1)
        self.dropout = QtWidgets.QLineEdit(self.BP)
        self.dropout.setEnabled(False)
        self.dropout.setMinimumSize(QtCore.QSize(80, 23))
        self.dropout.setMaximumSize(QtCore.QSize(80, 23))
        self.dropout.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.dropout.setFrame(True)
        self.dropout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dropout.setClearButtonEnabled(True)
        self.dropout.setObjectName("dropout")
        self.gridLayout_11.addWidget(self.dropout, 23, 1, 1, 1)
        self.lab_dropout = QtWidgets.QLabel(self.BP)
        self.lab_dropout.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_dropout.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_dropout.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_dropout.setObjectName("lab_dropout")
        self.gridLayout_11.addWidget(self.lab_dropout, 23, 0, 1, 1)
        self.HS_LossStep = QtWidgets.QSlider(self.BP)
        self.HS_LossStep.setMaximumSize(QtCore.QSize(80, 16777215))
        self.HS_LossStep.setMinimum(1)
        self.HS_LossStep.setMaximum(100)
        self.HS_LossStep.setProperty("value", 100)
        self.HS_LossStep.setOrientation(QtCore.Qt.Horizontal)
        self.HS_LossStep.setObjectName("HS_LossStep")
        self.gridLayout_11.addWidget(self.HS_LossStep, 21, 1, 1, 1)
        self.lab_LossStep = QtWidgets.QLabel(self.BP)
        self.lab_LossStep.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_LossStep.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_LossStep.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_LossStep.setObjectName("lab_LossStep")
        self.gridLayout_11.addWidget(self.lab_LossStep, 21, 0, 1, 1)
        self.trainEpoch = QtWidgets.QLineEdit(self.BP)
        self.trainEpoch.setMinimumSize(QtCore.QSize(80, 23))
        self.trainEpoch.setMaximumSize(QtCore.QSize(80, 23))
        self.trainEpoch.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.trainEpoch.setFrame(True)
        self.trainEpoch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainEpoch.setClearButtonEnabled(True)
        self.trainEpoch.setObjectName("trainEpoch")
        self.gridLayout_11.addWidget(self.trainEpoch, 20, 1, 1, 1)
        self.lab_trainEpoch = QtWidgets.QLabel(self.BP)
        self.lab_trainEpoch.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_trainEpoch.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_trainEpoch.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_trainEpoch.setObjectName("lab_trainEpoch")
        self.gridLayout_11.addWidget(self.lab_trainEpoch, 20, 0, 1, 1)
        self.cbb_aFunc_0 = QtWidgets.QComboBox(self.BP)
        self.cbb_aFunc_0.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_aFunc_0.setFrame(True)
        self.cbb_aFunc_0.setObjectName("cbb_aFunc_0")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.gridLayout_11.addWidget(self.cbb_aFunc_0, 8, 1, 1, 1)
        self.learningRate = QtWidgets.QLineEdit(self.BP)
        self.learningRate.setMinimumSize(QtCore.QSize(80, 23))
        self.learningRate.setMaximumSize(QtCore.QSize(80, 23))
        self.learningRate.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.learningRate.setFrame(True)
        self.learningRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.learningRate.setClearButtonEnabled(True)
        self.learningRate.setObjectName("learningRate")
        self.gridLayout_11.addWidget(self.learningRate, 15, 1, 1, 1)
        self.lab_output = QtWidgets.QLabel(self.BP)
        self.lab_output.setMinimumSize(QtCore.QSize(60, 23))
        self.lab_output.setMaximumSize(QtCore.QSize(60, 23))
        self.lab_output.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_output.setObjectName("lab_output")
        self.gridLayout_11.addWidget(self.lab_output, 11, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.BP)
        self.line_3.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_11.addWidget(self.line_3, 14, 0, 1, 2)
        self.outputLayer = QtWidgets.QLineEdit(self.BP)
        self.outputLayer.setMinimumSize(QtCore.QSize(80, 23))
        self.outputLayer.setMaximumSize(QtCore.QSize(80, 23))
        self.outputLayer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.outputLayer.setFrame(True)
        self.outputLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLayer.setClearButtonEnabled(True)
        self.outputLayer.setObjectName("outputLayer")
        self.gridLayout_11.addWidget(self.outputLayer, 11, 1, 1, 1)
        self.hideLayer_0 = QtWidgets.QLineEdit(self.BP)
        self.hideLayer_0.setMinimumSize(QtCore.QSize(80, 23))
        self.hideLayer_0.setMaximumSize(QtCore.QSize(80, 23))
        self.hideLayer_0.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.hideLayer_0.setFrame(True)
        self.hideLayer_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hideLayer_0.setClearButtonEnabled(True)
        self.hideLayer_0.setObjectName("hideLayer_0")
        self.gridLayout_11.addWidget(self.hideLayer_0, 7, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.BP)
        self.line_7.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout_11.addWidget(self.line_7, 4, 0, 1, 2)
        self.w_b_path = QtWidgets.QLineEdit(self.BP)
        self.w_b_path.setEnabled(True)
        self.w_b_path.setAcceptDrops(True)
        self.w_b_path.setText("")
        self.w_b_path.setFrame(True)
        self.w_b_path.setReadOnly(False)
        self.w_b_path.setClearButtonEnabled(True)
        self.w_b_path.setObjectName("w_b_path")
        self.gridLayout_11.addWidget(self.w_b_path, 3, 0, 1, 1)
        self.cbb_aFunc_output = QtWidgets.QComboBox(self.BP)
        self.cbb_aFunc_output.setMinimumSize(QtCore.QSize(80, 23))
        self.cbb_aFunc_output.setMaximumSize(QtCore.QSize(80, 23))
        self.cbb_aFunc_output.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_aFunc_output.setFrame(True)
        self.cbb_aFunc_output.setObjectName("cbb_aFunc_output")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.gridLayout_11.addWidget(self.cbb_aFunc_output, 13, 1, 1, 1)
        self.inputLayer = QtWidgets.QLineEdit(self.BP)
        self.inputLayer.setMinimumSize(QtCore.QSize(80, 23))
        self.inputLayer.setMaximumSize(QtCore.QSize(80, 23))
        self.inputLayer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputLayer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"\n"
"font: 9pt \"微软雅黑\";\n"
"")
        self.inputLayer.setText("")
        self.inputLayer.setFrame(True)
        self.inputLayer.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputLayer.setClearButtonEnabled(True)
        self.inputLayer.setObjectName("inputLayer")
        self.gridLayout_11.addWidget(self.inputLayer, 5, 1, 1, 1)
        self.cbb_database_BP = QtWidgets.QComboBox(self.BP)
        self.cbb_database_BP.setObjectName("cbb_database_BP")
        self.cbb_database_BP.addItem("")
        self.cbb_database_BP.addItem("")
        self.cbb_database_BP.addItem("")
        self.cbb_database_BP.addItem("")
        self.gridLayout_11.addWidget(self.cbb_database_BP, 0, 0, 1, 2)
        self.lab_learningRate = QtWidgets.QLabel(self.BP)
        self.lab_learningRate.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_learningRate.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_learningRate.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_learningRate.setObjectName("lab_learningRate")
        self.gridLayout_11.addWidget(self.lab_learningRate, 15, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.BP)
        self.line_1.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setLineWidth(1)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setObjectName("line_1")
        self.gridLayout_11.addWidget(self.line_1, 6, 0, 1, 2)
        self.cbb_lossFunc = QtWidgets.QComboBox(self.BP)
        self.cbb_lossFunc.setMinimumSize(QtCore.QSize(80, 21))
        self.cbb_lossFunc.setMaximumSize(QtCore.QSize(80, 21))
        self.cbb_lossFunc.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_lossFunc.setFrame(True)
        self.cbb_lossFunc.setObjectName("cbb_lossFunc")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.gridLayout_11.addWidget(self.cbb_lossFunc, 17, 1, 1, 1)
        self.btn_load_w_b = QtWidgets.QPushButton(self.BP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_w_b.sizePolicy().hasHeightForWidth())
        self.btn_load_w_b.setSizePolicy(sizePolicy)
        self.btn_load_w_b.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-打开文件夹-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_load_w_b.setIcon(icon2)
        self.btn_load_w_b.setIconSize(QtCore.QSize(24, 24))
        self.btn_load_w_b.setFlat(True)
        self.btn_load_w_b.setObjectName("btn_load_w_b")
        self.gridLayout_11.addWidget(self.btn_load_w_b, 3, 1, 1, 1)
        self.lab_optimizer = QtWidgets.QLabel(self.BP)
        self.lab_optimizer.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_optimizer.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_optimizer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_optimizer.setObjectName("lab_optimizer")
        self.gridLayout_11.addWidget(self.lab_optimizer, 16, 0, 1, 1)
        self.data_path = QtWidgets.QLineEdit(self.BP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_path.sizePolicy().hasHeightForWidth())
        self.data_path.setSizePolicy(sizePolicy)
        self.data_path.setText("")
        self.data_path.setClearButtonEnabled(True)
        self.data_path.setObjectName("data_path")
        self.gridLayout_11.addWidget(self.data_path, 1, 0, 1, 1)
        self.lab_lossFunc = QtWidgets.QLabel(self.BP)
        self.lab_lossFunc.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_lossFunc.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_lossFunc.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_lossFunc.setObjectName("lab_lossFunc")
        self.gridLayout_11.addWidget(self.lab_lossFunc, 17, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.BP)
        self.line_2.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_11.addWidget(self.line_2, 10, 0, 1, 2)
        self.cbb_optimizer = QtWidgets.QComboBox(self.BP)
        self.cbb_optimizer.setMinimumSize(QtCore.QSize(80, 21))
        self.cbb_optimizer.setMaximumSize(QtCore.QSize(80, 21))
        self.cbb_optimizer.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_optimizer.setMinimumContentsLength(0)
        self.cbb_optimizer.setFrame(True)
        self.cbb_optimizer.setModelColumn(0)
        self.cbb_optimizer.setObjectName("cbb_optimizer")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.gridLayout_11.addWidget(self.cbb_optimizer, 16, 1, 1, 1)
        self.lab_hide = QtWidgets.QLabel(self.BP)
        self.lab_hide.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_hide.setObjectName("lab_hide")
        self.gridLayout_11.addWidget(self.lab_hide, 7, 0, 1, 1)
        self.btn_load_data = QtWidgets.QPushButton(self.BP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_data.sizePolicy().hasHeightForWidth())
        self.btn_load_data.setSizePolicy(sizePolicy)
        self.btn_load_data.setText("")
        self.btn_load_data.setIcon(icon2)
        self.btn_load_data.setIconSize(QtCore.QSize(24, 24))
        self.btn_load_data.setFlat(True)
        self.btn_load_data.setObjectName("btn_load_data")
        self.gridLayout_11.addWidget(self.btn_load_data, 1, 1, 1, 1)
        self.toolBox.addItem(self.BP, "")
        self.GA = QtWidgets.QWidget()
        self.GA.setGeometry(QtCore.QRect(0, 0, 210, 583))
        self.GA.setObjectName("GA")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GA)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_startTrain_GA = QtWidgets.QPushButton(self.GA)
        self.btn_startTrain_GA.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_startTrain_GA.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_startTrain_GA.setText("")
        self.btn_startTrain_GA.setIcon(icon)
        self.btn_startTrain_GA.setIconSize(QtCore.QSize(35, 35))
        self.btn_startTrain_GA.setAutoDefault(False)
        self.btn_startTrain_GA.setDefault(False)
        self.btn_startTrain_GA.setFlat(True)
        self.btn_startTrain_GA.setObjectName("btn_startTrain_GA")
        self.gridLayout_4.addWidget(self.btn_startTrain_GA, 21, 1, 1, 1)
        self.GA_POP_SIZE = QtWidgets.QLineEdit(self.GA)
        self.GA_POP_SIZE.setEnabled(True)
        self.GA_POP_SIZE.setPlaceholderText("")
        self.GA_POP_SIZE.setObjectName("GA_POP_SIZE")
        self.gridLayout_4.addWidget(self.GA_POP_SIZE, 13, 1, 1, 2)
        self.btn_suspend_GA = QtWidgets.QPushButton(self.GA)
        self.btn_suspend_GA.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_suspend_GA.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_suspend_GA.setText("")
        self.btn_suspend_GA.setIcon(icon1)
        self.btn_suspend_GA.setIconSize(QtCore.QSize(35, 35))
        self.btn_suspend_GA.setAutoDefault(False)
        self.btn_suspend_GA.setDefault(False)
        self.btn_suspend_GA.setFlat(True)
        self.btn_suspend_GA.setObjectName("btn_suspend_GA")
        self.gridLayout_4.addWidget(self.btn_suspend_GA, 21, 0, 1, 1)
        self.lab_GA_CHROM = QtWidgets.QLabel(self.GA)
        self.lab_GA_CHROM.setObjectName("lab_GA_CHROM")
        self.gridLayout_4.addWidget(self.lab_GA_CHROM, 14, 0, 1, 1)
        self.checkBox_save_log = QtWidgets.QCheckBox(self.GA)
        self.checkBox_save_log.setObjectName("checkBox_save_log")
        self.gridLayout_4.addWidget(self.checkBox_save_log, 19, 0, 1, 1)
        self.lab_GA_epoch = QtWidgets.QLabel(self.GA)
        self.lab_GA_epoch.setObjectName("lab_GA_epoch")
        self.gridLayout_4.addWidget(self.lab_GA_epoch, 6, 0, 1, 1)
        self.GA_PM = QtWidgets.QLineEdit(self.GA)
        self.GA_PM.setObjectName("GA_PM")
        self.gridLayout_4.addWidget(self.GA_PM, 16, 1, 1, 2)
        self.lab_GA_PM = QtWidgets.QLabel(self.GA)
        self.lab_GA_PM.setObjectName("lab_GA_PM")
        self.gridLayout_4.addWidget(self.lab_GA_PM, 16, 0, 1, 1)
        self.lab_GA_GEN = QtWidgets.QLabel(self.GA)
        self.lab_GA_GEN.setObjectName("lab_GA_GEN")
        self.gridLayout_4.addWidget(self.lab_GA_GEN, 12, 0, 1, 1)
        self.btn_load_data_GA = QtWidgets.QPushButton(self.GA)
        self.btn_load_data_GA.setText("")
        self.btn_load_data_GA.setIcon(icon2)
        self.btn_load_data_GA.setIconSize(QtCore.QSize(24, 24))
        self.btn_load_data_GA.setFlat(True)
        self.btn_load_data_GA.setObjectName("btn_load_data_GA")
        self.gridLayout_4.addWidget(self.btn_load_data_GA, 1, 2, 1, 1)
        self.GA_PC = QtWidgets.QLineEdit(self.GA)
        self.GA_PC.setObjectName("GA_PC")
        self.gridLayout_4.addWidget(self.GA_PC, 15, 1, 1, 2)
        self.GA_CHROM = QtWidgets.QLineEdit(self.GA)
        self.GA_CHROM.setEnabled(True)
        self.GA_CHROM.setPlaceholderText("")
        self.GA_CHROM.setObjectName("GA_CHROM")
        self.gridLayout_4.addWidget(self.GA_CHROM, 14, 1, 1, 2)
        self.lab_GA_net = QtWidgets.QLabel(self.GA)
        self.lab_GA_net.setObjectName("lab_GA_net")
        self.gridLayout_4.addWidget(self.lab_GA_net, 2, 0, 1, 1)
        self.lab_GA_PC = QtWidgets.QLabel(self.GA)
        self.lab_GA_PC.setObjectName("lab_GA_PC")
        self.gridLayout_4.addWidget(self.lab_GA_PC, 15, 0, 1, 1)
        self.GA_net1 = QtWidgets.QSpinBox(self.GA)
        self.GA_net1.setMinimum(1)
        self.GA_net1.setProperty("value", 12)
        self.GA_net1.setObjectName("GA_net1")
        self.gridLayout_4.addWidget(self.GA_net1, 3, 1, 1, 2)
        self.GA_net2 = QtWidgets.QSpinBox(self.GA)
        self.GA_net2.setMinimum(1)
        self.GA_net2.setProperty("value", 1)
        self.GA_net2.setObjectName("GA_net2")
        self.gridLayout_4.addWidget(self.GA_net2, 4, 1, 1, 2)
        self.data_path_GA = QtWidgets.QLineEdit(self.GA)
        self.data_path_GA.setClearButtonEnabled(True)
        self.data_path_GA.setObjectName("data_path_GA")
        self.gridLayout_4.addWidget(self.data_path_GA, 1, 0, 1, 2)
        self.lab_GA_POP_SIZE = QtWidgets.QLabel(self.GA)
        self.lab_GA_POP_SIZE.setObjectName("lab_GA_POP_SIZE")
        self.gridLayout_4.addWidget(self.lab_GA_POP_SIZE, 13, 0, 1, 1)
        self.GA_NUM = QtWidgets.QLineEdit(self.GA)
        self.GA_NUM.setEnabled(True)
        self.GA_NUM.setReadOnly(False)
        self.GA_NUM.setPlaceholderText("")
        self.GA_NUM.setObjectName("GA_NUM")
        self.gridLayout_4.addWidget(self.GA_NUM, 10, 1, 1, 2)
        self.cbb_database_GA = QtWidgets.QComboBox(self.GA)
        self.cbb_database_GA.setObjectName("cbb_database_GA")
        self.cbb_database_GA.addItem("")
        self.cbb_database_GA.addItem("")
        self.cbb_database_GA.addItem("")
        self.cbb_database_GA.addItem("")
        self.gridLayout_4.addWidget(self.cbb_database_GA, 0, 0, 1, 3)
        self.GA_GEN = QtWidgets.QLineEdit(self.GA)
        self.GA_GEN.setEnabled(True)
        self.GA_GEN.setPlaceholderText("")
        self.GA_GEN.setObjectName("GA_GEN")
        self.gridLayout_4.addWidget(self.GA_GEN, 12, 1, 1, 2)
        self.GA_net0 = QtWidgets.QSpinBox(self.GA)
        self.GA_net0.setMinimum(1)
        self.GA_net0.setProperty("value", 13)
        self.GA_net0.setObjectName("GA_net0")
        self.gridLayout_4.addWidget(self.GA_net0, 2, 1, 1, 2)
        self.lab_GA_NUM = QtWidgets.QLabel(self.GA)
        self.lab_GA_NUM.setObjectName("lab_GA_NUM")
        self.gridLayout_4.addWidget(self.lab_GA_NUM, 10, 0, 1, 1)
        self.lab_GA_lr = QtWidgets.QLabel(self.GA)
        self.lab_GA_lr.setObjectName("lab_GA_lr")
        self.gridLayout_4.addWidget(self.lab_GA_lr, 5, 0, 1, 1)
        self.GA_lr = QtWidgets.QLineEdit(self.GA)
        self.GA_lr.setObjectName("GA_lr")
        self.gridLayout_4.addWidget(self.GA_lr, 5, 1, 1, 2)
        self.GA_epoch = QtWidgets.QLineEdit(self.GA)
        self.GA_epoch.setObjectName("GA_epoch")
        self.gridLayout_4.addWidget(self.GA_epoch, 6, 1, 1, 2)
        self.toolBox.addItem(self.GA, "")
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cbb_database_Search = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_database_Search.sizePolicy().hasHeightForWidth())
        self.cbb_database_Search.setSizePolicy(sizePolicy)
        self.cbb_database_Search.setMinimumSize(QtCore.QSize(200, 0))
        self.cbb_database_Search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbb_database_Search.setObjectName("cbb_database_Search")
        self.gridLayout_6.addWidget(self.cbb_database_Search, 0, 1, 1, 1)
        self.file_Search = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_Search.sizePolicy().hasHeightForWidth())
        self.file_Search.setSizePolicy(sizePolicy)
        self.file_Search.setMinimumSize(QtCore.QSize(300, 0))
        self.file_Search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.file_Search.setObjectName("file_Search")
        self.gridLayout_6.addWidget(self.file_Search, 0, 3, 1, 1)
        self.lab_file_Search = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_file_Search.sizePolicy().hasHeightForWidth())
        self.lab_file_Search.setSizePolicy(sizePolicy)
        self.lab_file_Search.setObjectName("lab_file_Search")
        self.gridLayout_6.addWidget(self.lab_file_Search, 0, 2, 1, 1)
        self.btn_browse_Search = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse_Search.sizePolicy().hasHeightForWidth())
        self.btn_browse_Search.setSizePolicy(sizePolicy)
        self.btn_browse_Search.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_browse_Search.setObjectName("btn_browse_Search")
        self.gridLayout_6.addWidget(self.btn_browse_Search, 0, 4, 1, 1)
        self.lab_database_Search = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_database_Search.sizePolicy().hasHeightForWidth())
        self.lab_database_Search.setSizePolicy(sizePolicy)
        self.lab_database_Search.setObjectName("lab_database_Search")
        self.gridLayout_6.addWidget(self.lab_database_Search, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 5, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 2, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableWidget_input = QtWidgets.QTableWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_input.sizePolicy().hasHeightForWidth())
        self.tableWidget_input.setSizePolicy(sizePolicy)
        self.tableWidget_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_input.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_input.setRowCount(1)
        self.tableWidget_input.setColumnCount(14)
        self.tableWidget_input.setObjectName("tableWidget_input")
        self.tableWidget_input.horizontalHeader().setDefaultSectionSize(65)
        self.tableWidget_input.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_input.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_13.addWidget(self.tableWidget_input, 0, 0, 1, 1)
        self.tableWidget_output = QtWidgets.QTableWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_output.sizePolicy().hasHeightForWidth())
        self.tableWidget_output.setSizePolicy(sizePolicy)
        self.tableWidget_output.setRowCount(5)
        self.tableWidget_output.setColumnCount(15)
        self.tableWidget_output.setObjectName("tableWidget_output")
        self.tableWidget_output.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_output.horizontalHeader().setDefaultSectionSize(65)
        self.tableWidget_output.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_output.verticalHeader().setStretchLastSection(False)
        self.gridLayout_13.addWidget(self.tableWidget_output, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_3, 1, 0, 2, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_inference = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_inference.sizePolicy().hasHeightForWidth())
        self.btn_inference.setSizePolicy(sizePolicy)
        self.btn_inference.setObjectName("btn_inference")
        self.gridLayout_8.addWidget(self.btn_inference, 0, 4, 1, 1)
        self.btn_case_search = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_case_search.sizePolicy().hasHeightForWidth())
        self.btn_case_search.setSizePolicy(sizePolicy)
        self.btn_case_search.setObjectName("btn_case_search")
        self.gridLayout_8.addWidget(self.btn_case_search, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 3, 1, 1)
        self.textEdit_inference = QtWidgets.QTextEdit(self.widget)
        self.textEdit_inference.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_inference.sizePolicy().hasHeightForWidth())
        self.textEdit_inference.setSizePolicy(sizePolicy)
        self.textEdit_inference.setReadOnly(True)
        self.textEdit_inference.setObjectName("textEdit_inference")
        self.gridLayout_8.addWidget(self.textEdit_inference, 1, 0, 1, 8)
        self.btn_weight = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_weight.sizePolicy().hasHeightForWidth())
        self.btn_weight.setSizePolicy(sizePolicy)
        self.btn_weight.setObjectName("btn_weight")
        self.gridLayout_8.addWidget(self.btn_weight, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 1, 1, 1)
        self.btn_case_search.raise_()
        self.btn_inference.raise_()
        self.textEdit_inference.raise_()
        self.btn_weight.raise_()
        self.gridLayout_7.addWidget(self.widget, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menutable = QtWidgets.QMenu(self.menu_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-data-sheet-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menutable.setIcon(icon3)
        self.menutable.setObjectName("menutable")
        self.menuinsert = QtWidgets.QMenu(self.menutable)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-table-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuinsert.setIcon(icon4)
        self.menuinsert.setObjectName("menuinsert")
        self.menudelete = QtWidgets.QMenu(self.menutable)
        self.menudelete.setObjectName("menudelete")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.about = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-关于-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon5)
        self.about.setObjectName("about")
        self.actionnew = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-file-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew.setIcon(icon6)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setIcon(icon2)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-save-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon7)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-export-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexit.setIcon(icon8)
        self.actionexit.setObjectName("actionexit")
        self.editUndo = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-撤销-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndo.setIcon(icon9)
        self.editUndo.setObjectName("editUndo")
        self.editRecover = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-恢复-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRecover.setIcon(icon10)
        self.editRecover.setObjectName("editRecover")
        self.editCopy = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-copy-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCopy.setIcon(icon11)
        self.editCopy.setObjectName("editCopy")
        self.editPaste = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-paste-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPaste.setIcon(icon12)
        self.editPaste.setObjectName("editPaste")
        self.editCrop = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-cut-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCrop.setIcon(icon13)
        self.editCrop.setObjectName("editCrop")
        self.editDelete = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-删除-bin-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editDelete.setIcon(icon14)
        self.editDelete.setObjectName("editDelete")
        self.insertRow = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-add-row-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertRow.setIcon(icon15)
        self.insertRow.setObjectName("insertRow")
        self.insertCol = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-add-column-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertCol.setIcon(icon16)
        self.insertCol.setObjectName("insertCol")
        self.deleteRow = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-delete-row-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteRow.setIcon(icon17)
        self.deleteRow.setObjectName("deleteRow")
        self.deleteCol = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-delete-column-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteCol.setIcon(icon18)
        self.deleteCol.setObjectName("deleteCol")
        self.menu.addAction(self.actionnew)
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionexit)
        self.menuinsert.addAction(self.insertRow)
        self.menuinsert.addAction(self.insertCol)
        self.menudelete.addAction(self.deleteRow)
        self.menudelete.addAction(self.deleteCol)
        self.menutable.addAction(self.menuinsert.menuAction())
        self.menutable.addAction(self.menudelete.menuAction())
        self.menu_2.addAction(self.editUndo)
        self.menu_2.addAction(self.editRecover)
        self.menu_2.addAction(self.editCopy)
        self.menu_2.addAction(self.editPaste)
        self.menu_2.addAction(self.editCrop)
        self.menu_2.addAction(self.editDelete)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menutable.menuAction())
        self.menu_4.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionnew)
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.insertRow)
        self.toolBar.addAction(self.insertCol)
        self.toolBar.addAction(self.deleteRow)
        self.toolBar.addAction(self.deleteCol)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editDelete)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cbb_aFunc_output.setCurrentIndex(4)
        self.cbb_optimizer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.userName, self.password)
        MainWindow.setTabOrder(self.password, self.btn_login)
        MainWindow.setTabOrder(self.btn_login, self.btn_exit)
        MainWindow.setTabOrder(self.btn_exit, self.cbb_database)
        MainWindow.setTabOrder(self.cbb_database, self.filePath)
        MainWindow.setTabOrder(self.filePath, self.btn_open)
        MainWindow.setTabOrder(self.btn_open, self.btn_upload)
        MainWindow.setTabOrder(self.btn_upload, self.lineEdit_search)
        MainWindow.setTabOrder(self.lineEdit_search, self.btn_execute)
        MainWindow.setTabOrder(self.btn_execute, self.table_data)
        MainWindow.setTabOrder(self.table_data, self.textEdit_database)
        MainWindow.setTabOrder(self.textEdit_database, self.cbb_database_BP)
        MainWindow.setTabOrder(self.cbb_database_BP, self.data_path)
        MainWindow.setTabOrder(self.data_path, self.btn_load_data)
        MainWindow.setTabOrder(self.btn_load_data, self.w_b_path)
        MainWindow.setTabOrder(self.w_b_path, self.btn_load_w_b)
        MainWindow.setTabOrder(self.btn_load_w_b, self.inputLayer)
        MainWindow.setTabOrder(self.inputLayer, self.hideLayer_0)
        MainWindow.setTabOrder(self.hideLayer_0, self.cbb_aFunc_0)
        MainWindow.setTabOrder(self.cbb_aFunc_0, self.outputLayer)
        MainWindow.setTabOrder(self.outputLayer, self.cbb_aFunc_output)
        MainWindow.setTabOrder(self.cbb_aFunc_output, self.learningRate)
        MainWindow.setTabOrder(self.learningRate, self.cbb_optimizer)
        MainWindow.setTabOrder(self.cbb_optimizer, self.cbb_lossFunc)
        MainWindow.setTabOrder(self.cbb_lossFunc, self.trainEpoch)
        MainWindow.setTabOrder(self.trainEpoch, self.HS_LossStep)
        MainWindow.setTabOrder(self.HS_LossStep, self.dropout)
        MainWindow.setTabOrder(self.dropout, self.dsb_testRate)
        MainWindow.setTabOrder(self.dsb_testRate, self.checkBox_saveImg)
        MainWindow.setTabOrder(self.checkBox_saveImg, self.btn_startTrain)
        MainWindow.setTabOrder(self.btn_startTrain, self.checkBox_saveModel)
        MainWindow.setTabOrder(self.checkBox_saveModel, self.btn_suspend)
        MainWindow.setTabOrder(self.btn_suspend, self.textEdit_trainResult)
        MainWindow.setTabOrder(self.textEdit_trainResult, self.cbb_database_GA)
        MainWindow.setTabOrder(self.cbb_database_GA, self.data_path_GA)
        MainWindow.setTabOrder(self.data_path_GA, self.btn_load_data_GA)
        MainWindow.setTabOrder(self.btn_load_data_GA, self.GA_net0)
        MainWindow.setTabOrder(self.GA_net0, self.GA_net1)
        MainWindow.setTabOrder(self.GA_net1, self.GA_net2)
        MainWindow.setTabOrder(self.GA_net2, self.GA_lr)
        MainWindow.setTabOrder(self.GA_lr, self.GA_epoch)
        MainWindow.setTabOrder(self.GA_epoch, self.GA_NUM)
        MainWindow.setTabOrder(self.GA_NUM, self.GA_GEN)
        MainWindow.setTabOrder(self.GA_GEN, self.GA_POP_SIZE)
        MainWindow.setTabOrder(self.GA_POP_SIZE, self.GA_CHROM)
        MainWindow.setTabOrder(self.GA_CHROM, self.GA_PC)
        MainWindow.setTabOrder(self.GA_PC, self.GA_PM)
        MainWindow.setTabOrder(self.GA_PM, self.checkBox_save_log)
        MainWindow.setTabOrder(self.checkBox_save_log, self.btn_suspend_GA)
        MainWindow.setTabOrder(self.btn_suspend_GA, self.btn_startTrain_GA)
        MainWindow.setTabOrder(self.btn_startTrain_GA, self.textEdit_inference)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "汽车冲压件智能CAPP系统"))
        self.lab_password.setText(_translate("MainWindow", "密  码："))
        self.btn_exit.setText(_translate("MainWindow", "退出"))
        self.lab_password_2.setText(_translate("MainWindow", "文  档："))
        self.lab_user.setText(_translate("MainWindow", "用户名："))
        self.textEdit_database.setPlaceholderText(_translate("MainWindow", "output:"))
        self.password.setText(_translate("MainWindow", "123456"))
        self.btn_login.setText(_translate("MainWindow", "登录"))
        self.lab_database.setText(_translate("MainWindow", "数据库："))
        self.cbb_database.setCurrentText(_translate("MainWindow", "请选择数据库"))
        self.cbb_database.setItemText(0, _translate("MainWindow", "请选择数据库"))
        self.cbb_database.setItemText(1, _translate("MainWindow", "material"))
        self.cbb_database.setItemText(2, _translate("MainWindow", "structure"))
        self.cbb_database.setItemText(3, _translate("MainWindow", "technology"))
        self.cbb_database.setItemText(4, _translate("MainWindow", "part_library"))
        self.userName.setText(_translate("MainWindow", "root"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "请输入mysql命令..."))
        self.btn_execute.setText(_translate("MainWindow", "执行"))
        self.btn_open.setText(_translate("MainWindow", "浏览..."))
        self.btn_upload.setText(_translate("MainWindow", "上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "数据管理"))
        self.lab_Epoch.setText(_translate("MainWindow", "Epoch:"))
        self.lab_input.setText(_translate("MainWindow", "输入层："))
        self.checkBox_saveImg.setText(_translate("MainWindow", "保存图片"))
        self.checkBox_saveModel.setText(_translate("MainWindow", "保存模型"))
        self.lab_dropout_2.setText(_translate("MainWindow", "test rate："))
        self.dropout.setText(_translate("MainWindow", "1"))
        self.lab_dropout.setText(_translate("MainWindow", "Dropout："))
        self.lab_LossStep.setText(_translate("MainWindow", "显示步长："))
        self.trainEpoch.setText(_translate("MainWindow", "1000"))
        self.lab_trainEpoch.setText(_translate("MainWindow", "训练周期："))
        self.cbb_aFunc_0.setItemText(0, _translate("MainWindow", "sigmoid"))
        self.cbb_aFunc_0.setItemText(1, _translate("MainWindow", "relu"))
        self.cbb_aFunc_0.setItemText(2, _translate("MainWindow", "tanh"))
        self.cbb_aFunc_0.setItemText(3, _translate("MainWindow", "softmax"))
        self.cbb_aFunc_0.setItemText(4, _translate("MainWindow", "None"))
        self.learningRate.setText(_translate("MainWindow", "0.01"))
        self.lab_output.setText(_translate("MainWindow", "输出层："))
        self.outputLayer.setText(_translate("MainWindow", "1"))
        self.hideLayer_0.setText(_translate("MainWindow", "12"))
        self.w_b_path.setPlaceholderText(_translate("MainWindow", "读取权值/偏置..."))
        self.cbb_aFunc_output.setItemText(0, _translate("MainWindow", "sigmoid"))
        self.cbb_aFunc_output.setItemText(1, _translate("MainWindow", "relu"))
        self.cbb_aFunc_output.setItemText(2, _translate("MainWindow", "tanh"))
        self.cbb_aFunc_output.setItemText(3, _translate("MainWindow", "softmax"))
        self.cbb_aFunc_output.setItemText(4, _translate("MainWindow", "None"))
        self.cbb_database_BP.setItemText(0, _translate("MainWindow", "请选择数据库"))
        self.cbb_database_BP.setItemText(1, _translate("MainWindow", "material"))
        self.cbb_database_BP.setItemText(2, _translate("MainWindow", "structure"))
        self.cbb_database_BP.setItemText(3, _translate("MainWindow", "technology"))
        self.lab_learningRate.setText(_translate("MainWindow", "学习率："))
        self.cbb_lossFunc.setItemText(0, _translate("MainWindow", "MSE"))
        self.cbb_lossFunc.setItemText(1, _translate("MainWindow", "RMSE"))
        self.cbb_lossFunc.setItemText(2, _translate("MainWindow", "MRE"))
        self.cbb_lossFunc.setItemText(3, _translate("MainWindow", "MAE"))
        self.cbb_lossFunc.setItemText(4, _translate("MainWindow", "R-squared"))
        self.cbb_lossFunc.setItemText(5, _translate("MainWindow", "None"))
        self.lab_optimizer.setText(_translate("MainWindow", "优化器："))
        self.data_path.setPlaceholderText(_translate("MainWindow", "读取本地数据..."))
        self.lab_lossFunc.setText(_translate("MainWindow", "评价指标："))
        self.cbb_optimizer.setItemText(0, _translate("MainWindow", "AdamOptimizer"))
        self.cbb_optimizer.setItemText(1, _translate("MainWindow", "AdagradOptimizer"))
        self.cbb_optimizer.setItemText(2, _translate("MainWindow", "AdagradDAOptimizer"))
        self.cbb_optimizer.setItemText(3, _translate("MainWindow", "FtrlOptimizer"))
        self.cbb_optimizer.setItemText(4, _translate("MainWindow", "GradientDescentOptimizer"))
        self.cbb_optimizer.setItemText(5, _translate("MainWindow", "MomentumOptimizer"))
        self.cbb_optimizer.setItemText(6, _translate("MainWindow", "ProximalAdagradOptimizer"))
        self.cbb_optimizer.setItemText(7, _translate("MainWindow", "ProximalGradientDescentOptimizer"))
        self.cbb_optimizer.setItemText(8, _translate("MainWindow", "RMSPropOptimizer"))
        self.lab_hide.setText(_translate("MainWindow", "隐藏层："))
        self.GA_POP_SIZE.setText(_translate("MainWindow", "20"))
        self.lab_GA_CHROM.setText(_translate("MainWindow", "染色体："))
        self.checkBox_save_log.setText(_translate("MainWindow", "保存数据"))
        self.lab_GA_epoch.setText(_translate("MainWindow", "训练周期："))
        self.GA_PM.setText(_translate("MainWindow", "0.01"))
        self.GA_PM.setPlaceholderText(_translate("MainWindow", "0.0001-0.1"))
        self.lab_GA_PM.setText(_translate("MainWindow", "变异概率："))
        self.lab_GA_GEN.setText(_translate("MainWindow", "遗传代数："))
        self.GA_PC.setText(_translate("MainWindow", "0.7"))
        self.GA_PC.setPlaceholderText(_translate("MainWindow", "0.4-0.99"))
        self.GA_CHROM.setText(_translate("MainWindow", "10"))
        self.lab_GA_net.setText(_translate("MainWindow", "网络结构："))
        self.lab_GA_PC.setText(_translate("MainWindow", "交叉概率："))
        self.data_path_GA.setPlaceholderText(_translate("MainWindow", "读取本地数据..."))
        self.lab_GA_POP_SIZE.setText(_translate("MainWindow", "种群规模："))
        self.cbb_database_GA.setItemText(0, _translate("MainWindow", "请选择数据库"))
        self.cbb_database_GA.setItemText(1, _translate("MainWindow", "material"))
        self.cbb_database_GA.setItemText(2, _translate("MainWindow", "structure"))
        self.cbb_database_GA.setItemText(3, _translate("MainWindow", "technology"))
        self.GA_GEN.setText(_translate("MainWindow", "20"))
        self.lab_GA_NUM.setText(_translate("MainWindow", "优化参数："))
        self.lab_GA_lr.setText(_translate("MainWindow", "学习率："))
        self.GA_lr.setText(_translate("MainWindow", "0.1"))
        self.GA_lr.setPlaceholderText(_translate("MainWindow", "0.1-0.001"))
        self.GA_epoch.setText(_translate("MainWindow", "100"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "智能学习"))
        self.lab_file_Search.setText(_translate("MainWindow", "文档："))
        self.btn_browse_Search.setText(_translate("MainWindow", "浏览..."))
        self.lab_database_Search.setText(_translate("MainWindow", "数据库："))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox.setItemText(0, _translate("MainWindow", "横截面"))
        self.comboBox.setItemText(1, _translate("MainWindow", "纵轴线"))
        self.comboBox.setItemText(2, _translate("MainWindow", "局部特征"))
        self.btn_inference.setText(_translate("MainWindow", "推理分析"))
        self.btn_case_search.setText(_translate("MainWindow", "案例检索"))
        self.btn_weight.setText(_translate("MainWindow", "特征权重"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "专家推理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "知识采集"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menutable.setTitle(_translate("MainWindow", "table"))
        self.menuinsert.setTitle(_translate("MainWindow", "insert"))
        self.menudelete.setTitle(_translate("MainWindow", "delete"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.about.setText(_translate("MainWindow", "about"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.editUndo.setText(_translate("MainWindow", "undo"))
        self.editRecover.setText(_translate("MainWindow", "recover"))
        self.editCopy.setText(_translate("MainWindow", "copy"))
        self.editPaste.setText(_translate("MainWindow", "paste"))
        self.editCrop.setText(_translate("MainWindow", "crop"))
        self.editDelete.setText(_translate("MainWindow", "delete"))
        self.insertRow.setText(_translate("MainWindow", "row"))
        self.insertCol.setText(_translate("MainWindow", "col"))
        self.deleteRow.setText(_translate("MainWindow", "row"))
        self.deleteCol.setText(_translate("MainWindow", "col"))

import resources_rc
