# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 803)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_password = QtWidgets.QLabel(self.tab)
        self.lab_password.setObjectName("lab_password")
        self.gridLayout.addWidget(self.lab_password, 0, 4, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(self.tab)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 0, 7, 1, 1)
        self.lab_password_2 = QtWidgets.QLabel(self.tab)
        self.lab_password_2.setObjectName("lab_password_2")
        self.gridLayout.addWidget(self.lab_password_2, 2, 4, 1, 1)
        self.filePath = QtWidgets.QLineEdit(self.tab)
        self.filePath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 2, 5, 1, 1)
        self.lab_user = QtWidgets.QLabel(self.tab)
        self.lab_user.setObjectName("lab_user")
        self.gridLayout.addWidget(self.lab_user, 0, 2, 1, 1)
        self.textEdit_database = QtWidgets.QTextEdit(self.tab)
        self.textEdit_database.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_database.sizePolicy().hasHeightForWidth())
        self.textEdit_database.setSizePolicy(sizePolicy)
        self.textEdit_database.setMinimumSize(QtCore.QSize(256, 417))
        self.textEdit_database.setReadOnly(True)
        self.textEdit_database.setObjectName("textEdit_database")
        self.gridLayout.addWidget(self.textEdit_database, 6, 9, 1, 1)
        self.password = QtWidgets.QLineEdit(self.tab)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 0, 5, 1, 1)
        self.table_data = QtWidgets.QTableWidget(self.tab)
        self.table_data.setRowCount(50)
        self.table_data.setColumnCount(8)
        self.table_data.setObjectName("table_data")
        self.gridLayout.addWidget(self.table_data, 6, 0, 1, 9)
        self.btn_login = QtWidgets.QPushButton(self.tab)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 0, 6, 1, 1)
        self.lab_database = QtWidgets.QLabel(self.tab)
        self.lab_database.setObjectName("lab_database")
        self.gridLayout.addWidget(self.lab_database, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 2)
        self.cbb_database = QtWidgets.QComboBox(self.tab)
        self.cbb_database.setObjectName("cbb_database")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.cbb_database.addItem("")
        self.gridLayout.addWidget(self.cbb_database, 2, 3, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.tab)
        self.userName.setClearButtonEnabled(True)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 0, 3, 1, 1)
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_search.setClearButtonEnabled(True)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout.addWidget(self.lineEdit_search, 3, 2, 1, 4)
        self.btn_execute = QtWidgets.QPushButton(self.tab)
        self.btn_execute.setObjectName("btn_execute")
        self.gridLayout.addWidget(self.btn_execute, 3, 6, 1, 1)
        self.btn_open = QtWidgets.QPushButton(self.tab)
        self.btn_open.setObjectName("btn_open")
        self.gridLayout.addWidget(self.btn_open, 2, 6, 1, 1)
        self.btn_upload = QtWidgets.QPushButton(self.tab)
        self.btn_upload.setObjectName("btn_upload")
        self.gridLayout.addWidget(self.btn_upload, 2, 7, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_trainProcess = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_trainProcess.sizePolicy().hasHeightForWidth())
        self.frame_trainProcess.setSizePolicy(sizePolicy)
        self.frame_trainProcess.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"border-radius: 5px;")
        self.frame_trainProcess.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_trainProcess.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_trainProcess.setLineWidth(3)
        self.frame_trainProcess.setMidLineWidth(3)
        self.frame_trainProcess.setObjectName("frame_trainProcess")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_trainProcess)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_plot_2 = QtWidgets.QWidget(self.frame_trainProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_2.sizePolicy().hasHeightForWidth())
        self.widget_plot_2.setSizePolicy(sizePolicy)
        self.widget_plot_2.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(38, 39, 33);")
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.gridLayout_5.addWidget(self.widget_plot_2, 1, 1, 1, 1)
        self.widget_plot_1 = QtWidgets.QWidget(self.frame_trainProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_1.sizePolicy().hasHeightForWidth())
        self.widget_plot_1.setSizePolicy(sizePolicy)
        self.widget_plot_1.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(38, 39, 33);")
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.gridLayout_5.addWidget(self.widget_plot_1, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lcd_epoch = QtWidgets.QLCDNumber(self.frame_trainProcess)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_epoch.setFont(font)
        self.lcd_epoch.setStyleSheet("\n"
"color: rgb(0, 255, 0);\n"
"background-color: rgb(60, 63, 65);\n"
"")
        self.lcd_epoch.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_epoch.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcd_epoch.setLineWidth(2)
        self.lcd_epoch.setMidLineWidth(0)
        self.lcd_epoch.setDigitCount(6)
        self.lcd_epoch.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_epoch.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_epoch.setProperty("value", 0.0)
        self.lcd_epoch.setProperty("intValue", 0)
        self.lcd_epoch.setObjectName("lcd_epoch")
        self.gridLayout_9.addWidget(self.lcd_epoch, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 2, 1, 1)
        self.lab_Epoch = QtWidgets.QLabel(self.frame_trainProcess)
        self.lab_Epoch.setStyleSheet("color: rgb(255, 111, 0);\n"
"background-color: rgb(201, 201, 200);\n"
"font: 75 10pt \"微软雅黑\";")
        self.lab_Epoch.setObjectName("lab_Epoch")
        self.gridLayout_9.addWidget(self.lab_Epoch, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_trainProcess, 0, 2, 1, 1)
        self.textEdit_trainResult = QtWidgets.QTextEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_trainResult.sizePolicy().hasHeightForWidth())
        self.textEdit_trainResult.setSizePolicy(sizePolicy)
        self.textEdit_trainResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_trainResult.setStyleSheet("border-radius:5px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(240, 240, 240);\n"
"background-color: rgb(60, 63, 65);\n"
"")
        self.textEdit_trainResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_trainResult.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_trainResult.setLineWidth(3)
        self.textEdit_trainResult.setMidLineWidth(3)
        self.textEdit_trainResult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_trainResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_trainResult.setObjectName("textEdit_trainResult")
        self.gridLayout_2.addWidget(self.textEdit_trainResult, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(210, 480))
        self.groupBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.groupBox.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.learningRate = QtWidgets.QLineEdit(self.groupBox)
        self.learningRate.setMinimumSize(QtCore.QSize(80, 23))
        self.learningRate.setMaximumSize(QtCore.QSize(80, 23))
        self.learningRate.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.learningRate.setFrame(True)
        self.learningRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.learningRate.setClearButtonEnabled(True)
        self.learningRate.setObjectName("learningRate")
        self.gridLayout_11.addWidget(self.learningRate, 11, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_11.addWidget(self.line_2, 6, 0, 1, 2)
        self.lab_input = QtWidgets.QLabel(self.groupBox)
        self.lab_input.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_input.setObjectName("lab_input")
        self.gridLayout_11.addWidget(self.lab_input, 1, 0, 1, 1)
        self.lab_optimizer = QtWidgets.QLabel(self.groupBox)
        self.lab_optimizer.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_optimizer.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_optimizer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_optimizer.setObjectName("lab_optimizer")
        self.gridLayout_11.addWidget(self.lab_optimizer, 12, 0, 1, 1)
        self.inputLayer = QtWidgets.QLineEdit(self.groupBox)
        self.inputLayer.setMinimumSize(QtCore.QSize(80, 23))
        self.inputLayer.setMaximumSize(QtCore.QSize(80, 23))
        self.inputLayer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputLayer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"\n"
"font: 9pt \"微软雅黑\";\n"
"")
        self.inputLayer.setText("")
        self.inputLayer.setFrame(True)
        self.inputLayer.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputLayer.setClearButtonEnabled(True)
        self.inputLayer.setObjectName("inputLayer")
        self.gridLayout_11.addWidget(self.inputLayer, 1, 1, 1, 1)
        self.cbb_aFunc_output = QtWidgets.QComboBox(self.groupBox)
        self.cbb_aFunc_output.setMinimumSize(QtCore.QSize(80, 23))
        self.cbb_aFunc_output.setMaximumSize(QtCore.QSize(80, 23))
        self.cbb_aFunc_output.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_aFunc_output.setFrame(True)
        self.cbb_aFunc_output.setObjectName("cbb_aFunc_output")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.cbb_aFunc_output.addItem("")
        self.gridLayout_11.addWidget(self.cbb_aFunc_output, 9, 1, 1, 1)
        self.lab_learningRate = QtWidgets.QLabel(self.groupBox)
        self.lab_learningRate.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_learningRate.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_learningRate.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_learningRate.setObjectName("lab_learningRate")
        self.gridLayout_11.addWidget(self.lab_learningRate, 11, 0, 1, 1)
        self.lab_lossFunc = QtWidgets.QLabel(self.groupBox)
        self.lab_lossFunc.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_lossFunc.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_lossFunc.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_lossFunc.setObjectName("lab_lossFunc")
        self.gridLayout_11.addWidget(self.lab_lossFunc, 13, 0, 1, 1)
        self.dropout = QtWidgets.QLineEdit(self.groupBox)
        self.dropout.setEnabled(False)
        self.dropout.setMinimumSize(QtCore.QSize(80, 23))
        self.dropout.setMaximumSize(QtCore.QSize(80, 23))
        self.dropout.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.dropout.setFrame(True)
        self.dropout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dropout.setClearButtonEnabled(True)
        self.dropout.setObjectName("dropout")
        self.gridLayout_11.addWidget(self.dropout, 19, 1, 1, 1)
        self.btn_startTrain = QtWidgets.QPushButton(self.groupBox)
        self.btn_startTrain.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_startTrain.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_startTrain.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-play-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_startTrain.setIcon(icon)
        self.btn_startTrain.setIconSize(QtCore.QSize(35, 35))
        self.btn_startTrain.setAutoDefault(False)
        self.btn_startTrain.setDefault(False)
        self.btn_startTrain.setFlat(True)
        self.btn_startTrain.setObjectName("btn_startTrain")
        self.gridLayout_11.addWidget(self.btn_startTrain, 22, 1, 1, 1)
        self.dsb_testRate = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_testRate.setFrame(True)
        self.dsb_testRate.setDecimals(1)
        self.dsb_testRate.setMinimum(0.1)
        self.dsb_testRate.setMaximum(1.0)
        self.dsb_testRate.setSingleStep(0.1)
        self.dsb_testRate.setProperty("value", 0.1)
        self.dsb_testRate.setObjectName("dsb_testRate")
        self.gridLayout_11.addWidget(self.dsb_testRate, 20, 1, 1, 1)
        self.cbb_optimizer = QtWidgets.QComboBox(self.groupBox)
        self.cbb_optimizer.setMinimumSize(QtCore.QSize(80, 21))
        self.cbb_optimizer.setMaximumSize(QtCore.QSize(80, 21))
        self.cbb_optimizer.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_optimizer.setMinimumContentsLength(0)
        self.cbb_optimizer.setFrame(True)
        self.cbb_optimizer.setModelColumn(0)
        self.cbb_optimizer.setObjectName("cbb_optimizer")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.cbb_optimizer.addItem("")
        self.gridLayout_11.addWidget(self.cbb_optimizer, 12, 1, 1, 1)
        self.lab_trainEpoch = QtWidgets.QLabel(self.groupBox)
        self.lab_trainEpoch.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_trainEpoch.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_trainEpoch.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_trainEpoch.setObjectName("lab_trainEpoch")
        self.gridLayout_11.addWidget(self.lab_trainEpoch, 16, 0, 1, 1)
        self.lab_dropout = QtWidgets.QLabel(self.groupBox)
        self.lab_dropout.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_dropout.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_dropout.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_dropout.setObjectName("lab_dropout")
        self.gridLayout_11.addWidget(self.lab_dropout, 19, 0, 1, 1)
        self.checkBox_saveModel = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_saveModel.setMinimumSize(QtCore.QSize(70, 23))
        self.checkBox_saveModel.setMaximumSize(QtCore.QSize(70, 23))
        self.checkBox_saveModel.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 8pt \"微软雅黑\";")
        self.checkBox_saveModel.setChecked(True)
        self.checkBox_saveModel.setObjectName("checkBox_saveModel")
        self.gridLayout_11.addWidget(self.checkBox_saveModel, 21, 0, 1, 1)
        self.checkBox_saveImg = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_saveImg.setMinimumSize(QtCore.QSize(70, 23))
        self.checkBox_saveImg.setMaximumSize(QtCore.QSize(70, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_saveImg.setFont(font)
        self.checkBox_saveImg.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 8pt \"微软雅黑\";")
        self.checkBox_saveImg.setChecked(True)
        self.checkBox_saveImg.setObjectName("checkBox_saveImg")
        self.gridLayout_11.addWidget(self.checkBox_saveImg, 21, 1, 1, 1)
        self.lab_dropout_2 = QtWidgets.QLabel(self.groupBox)
        self.lab_dropout_2.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_dropout_2.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_dropout_2.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_dropout_2.setObjectName("lab_dropout_2")
        self.gridLayout_11.addWidget(self.lab_dropout_2, 20, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_11.addWidget(self.line_3, 10, 0, 1, 2)
        self.trainEpoch = QtWidgets.QLineEdit(self.groupBox)
        self.trainEpoch.setMinimumSize(QtCore.QSize(80, 23))
        self.trainEpoch.setMaximumSize(QtCore.QSize(80, 23))
        self.trainEpoch.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.trainEpoch.setFrame(True)
        self.trainEpoch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainEpoch.setClearButtonEnabled(True)
        self.trainEpoch.setObjectName("trainEpoch")
        self.gridLayout_11.addWidget(self.trainEpoch, 16, 1, 1, 1)
        self.btn_suspend = QtWidgets.QPushButton(self.groupBox)
        self.btn_suspend.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_suspend.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.btn_suspend.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-stop-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_suspend.setIcon(icon1)
        self.btn_suspend.setIconSize(QtCore.QSize(35, 35))
        self.btn_suspend.setAutoDefault(False)
        self.btn_suspend.setDefault(False)
        self.btn_suspend.setFlat(True)
        self.btn_suspend.setObjectName("btn_suspend")
        self.gridLayout_11.addWidget(self.btn_suspend, 22, 0, 1, 1)
        self.cbb_lossFunc = QtWidgets.QComboBox(self.groupBox)
        self.cbb_lossFunc.setMinimumSize(QtCore.QSize(80, 21))
        self.cbb_lossFunc.setMaximumSize(QtCore.QSize(80, 21))
        self.cbb_lossFunc.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_lossFunc.setFrame(True)
        self.cbb_lossFunc.setObjectName("cbb_lossFunc")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.cbb_lossFunc.addItem("")
        self.gridLayout_11.addWidget(self.cbb_lossFunc, 13, 1, 1, 1)
        self.lab_hide = QtWidgets.QLabel(self.groupBox)
        self.lab_hide.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_hide.setObjectName("lab_hide")
        self.gridLayout_11.addWidget(self.lab_hide, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.data_path = QtWidgets.QLineEdit(self.widget)
        self.data_path.setClearButtonEnabled(True)
        self.data_path.setObjectName("data_path")
        self.gridLayout_6.addWidget(self.data_path, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 0, 0, 1, 2)
        self.btn_load_data = QtWidgets.QPushButton(self.widget)
        self.btn_load_data.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-打开文件夹-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_load_data.setIcon(icon2)
        self.btn_load_data.setIconSize(QtCore.QSize(24, 24))
        self.btn_load_data.setFlat(True)
        self.btn_load_data.setObjectName("btn_load_data")
        self.gridLayout_6.addWidget(self.btn_load_data, 1, 1, 1, 1)
        self.w_b_path = QtWidgets.QLineEdit(self.widget)
        self.w_b_path.setEnabled(True)
        self.w_b_path.setAcceptDrops(True)
        self.w_b_path.setText("")
        self.w_b_path.setFrame(True)
        self.w_b_path.setReadOnly(False)
        self.w_b_path.setClearButtonEnabled(True)
        self.w_b_path.setObjectName("w_b_path")
        self.gridLayout_6.addWidget(self.w_b_path, 2, 0, 1, 1)
        self.btn_load_w_b = QtWidgets.QPushButton(self.widget)
        self.btn_load_w_b.setText("")
        self.btn_load_w_b.setIcon(icon2)
        self.btn_load_w_b.setIconSize(QtCore.QSize(24, 24))
        self.btn_load_w_b.setFlat(True)
        self.btn_load_w_b.setObjectName("btn_load_w_b")
        self.gridLayout_6.addWidget(self.btn_load_w_b, 2, 1, 1, 1)
        self.gridLayout_11.addWidget(self.widget, 0, 0, 1, 2)
        self.lab_LossStep = QtWidgets.QLabel(self.groupBox)
        self.lab_LossStep.setMinimumSize(QtCore.QSize(80, 23))
        self.lab_LossStep.setMaximumSize(QtCore.QSize(80, 23))
        self.lab_LossStep.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_LossStep.setObjectName("lab_LossStep")
        self.gridLayout_11.addWidget(self.lab_LossStep, 17, 0, 1, 1)
        self.HS_LossStep = QtWidgets.QSlider(self.groupBox)
        self.HS_LossStep.setMaximumSize(QtCore.QSize(80, 16777215))
        self.HS_LossStep.setMinimum(1)
        self.HS_LossStep.setMaximum(100)
        self.HS_LossStep.setProperty("value", 100)
        self.HS_LossStep.setOrientation(QtCore.Qt.Horizontal)
        self.HS_LossStep.setObjectName("HS_LossStep")
        self.gridLayout_11.addWidget(self.HS_LossStep, 17, 1, 1, 1)
        self.outputLayer = QtWidgets.QLineEdit(self.groupBox)
        self.outputLayer.setMinimumSize(QtCore.QSize(80, 23))
        self.outputLayer.setMaximumSize(QtCore.QSize(80, 23))
        self.outputLayer.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.outputLayer.setFrame(True)
        self.outputLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLayer.setClearButtonEnabled(True)
        self.outputLayer.setObjectName("outputLayer")
        self.gridLayout_11.addWidget(self.outputLayer, 7, 1, 1, 1)
        self.cbb_aFunc_0 = QtWidgets.QComboBox(self.groupBox)
        self.cbb_aFunc_0.setStyleSheet("background-color: rgb(196, 196, 195);\n"
"font: 9pt \"微软雅黑\";")
        self.cbb_aFunc_0.setFrame(True)
        self.cbb_aFunc_0.setObjectName("cbb_aFunc_0")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.cbb_aFunc_0.addItem("")
        self.gridLayout_11.addWidget(self.cbb_aFunc_0, 4, 1, 1, 1)
        self.lab_output = QtWidgets.QLabel(self.groupBox)
        self.lab_output.setMinimumSize(QtCore.QSize(60, 23))
        self.lab_output.setMaximumSize(QtCore.QSize(60, 23))
        self.lab_output.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.lab_output.setObjectName("lab_output")
        self.gridLayout_11.addWidget(self.lab_output, 7, 0, 1, 1)
        self.hideLayer_0 = QtWidgets.QLineEdit(self.groupBox)
        self.hideLayer_0.setMinimumSize(QtCore.QSize(80, 23))
        self.hideLayer_0.setMaximumSize(QtCore.QSize(80, 23))
        self.hideLayer_0.setStyleSheet("background-color: rgb(201, 201, 200);\n"
"font: 9pt \"微软雅黑\";")
        self.hideLayer_0.setFrame(True)
        self.hideLayer_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hideLayer_0.setClearButtonEnabled(True)
        self.hideLayer_0.setObjectName("hideLayer_0")
        self.gridLayout_11.addWidget(self.hideLayer_0, 3, 1, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.groupBox)
        self.line_1.setStyleSheet("background-color: rgb(236, 248, 255);")
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setLineWidth(1)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setObjectName("line_1")
        self.gridLayout_11.addWidget(self.line_1, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gb_processPeremeter = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_processPeremeter.sizePolicy().hasHeightForWidth())
        self.gb_processPeremeter.setSizePolicy(sizePolicy)
        self.gb_processPeremeter.setObjectName("gb_processPeremeter")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gb_processPeremeter)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lab_friction = QtWidgets.QLabel(self.gb_processPeremeter)
        self.lab_friction.setObjectName("lab_friction")
        self.gridLayout_15.addWidget(self.lab_friction, 2, 0, 1, 1)
        self.friction = QtWidgets.QLineEdit(self.gb_processPeremeter)
        self.friction.setObjectName("friction")
        self.gridLayout_15.addWidget(self.friction, 2, 1, 1, 1)
        self.drawBead = QtWidgets.QLineEdit(self.gb_processPeremeter)
        self.drawBead.setObjectName("drawBead")
        self.gridLayout_15.addWidget(self.drawBead, 4, 1, 1, 1)
        self.lab_drawBead = QtWidgets.QLabel(self.gb_processPeremeter)
        self.lab_drawBead.setObjectName("lab_drawBead")
        self.gridLayout_15.addWidget(self.lab_drawBead, 4, 0, 1, 1)
        self.lab_velocity = QtWidgets.QLabel(self.gb_processPeremeter)
        self.lab_velocity.setObjectName("lab_velocity")
        self.gridLayout_15.addWidget(self.lab_velocity, 0, 0, 1, 1)
        self.lab_gap = QtWidgets.QLabel(self.gb_processPeremeter)
        self.lab_gap.setObjectName("lab_gap")
        self.gridLayout_15.addWidget(self.lab_gap, 3, 0, 1, 1)
        self.pressure = QtWidgets.QLineEdit(self.gb_processPeremeter)
        self.pressure.setObjectName("pressure")
        self.gridLayout_15.addWidget(self.pressure, 1, 1, 1, 1)
        self.gap = QtWidgets.QLineEdit(self.gb_processPeremeter)
        self.gap.setObjectName("gap")
        self.gridLayout_15.addWidget(self.gap, 3, 1, 1, 1)
        self.velocity = QtWidgets.QLineEdit(self.gb_processPeremeter)
        self.velocity.setObjectName("velocity")
        self.gridLayout_15.addWidget(self.velocity, 0, 1, 1, 1)
        self.lab_pressure = QtWidgets.QLabel(self.gb_processPeremeter)
        self.lab_pressure.setObjectName("lab_pressure")
        self.gridLayout_15.addWidget(self.lab_pressure, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.gb_processPeremeter, 0, 1, 2, 1)
        self.gb_materialProperty = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_materialProperty.sizePolicy().hasHeightForWidth())
        self.gb_materialProperty.setSizePolicy(sizePolicy)
        self.gb_materialProperty.setObjectName("gb_materialProperty")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gb_materialProperty)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.yield_strength = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.yield_strength.setObjectName("yield_strength")
        self.gridLayout_12.addWidget(self.yield_strength, 8, 1, 1, 1)
        self.lab_tensile = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_tensile.setObjectName("lab_tensile")
        self.gridLayout_12.addWidget(self.lab_tensile, 6, 0, 1, 1)
        self.lab_yield = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_yield.setObjectName("lab_yield")
        self.gridLayout_12.addWidget(self.lab_yield, 8, 0, 1, 1)
        self.PH = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.PH.setObjectName("PH")
        self.gridLayout_12.addWidget(self.PH, 0, 1, 1, 1)
        self.lab_n = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_n.setObjectName("lab_n")
        self.gridLayout_12.addWidget(self.lab_n, 4, 0, 1, 1)
        self.tensile_strength = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.tensile_strength.setObjectName("tensile_strength")
        self.gridLayout_12.addWidget(self.tensile_strength, 6, 1, 1, 1)
        self.nValue = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.nValue.setObjectName("nValue")
        self.gridLayout_12.addWidget(self.nValue, 4, 1, 1, 1)
        self.elongation = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.elongation.setObjectName("elongation")
        self.gridLayout_12.addWidget(self.elongation, 2, 1, 1, 1)
        self.lab_PH = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_PH.setObjectName("lab_PH")
        self.gridLayout_12.addWidget(self.lab_PH, 0, 0, 1, 1)
        self.lab_elongation = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_elongation.setObjectName("lab_elongation")
        self.gridLayout_12.addWidget(self.lab_elongation, 2, 0, 1, 1)
        self.rValue = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.rValue.setObjectName("rValue")
        self.gridLayout_12.addWidget(self.rValue, 5, 1, 1, 1)
        self.lab_r = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_r.setObjectName("lab_r")
        self.gridLayout_12.addWidget(self.lab_r, 5, 0, 1, 1)
        self.lab_thickness = QtWidgets.QLabel(self.gb_materialProperty)
        self.lab_thickness.setObjectName("lab_thickness")
        self.gridLayout_12.addWidget(self.lab_thickness, 1, 0, 1, 1)
        self.thickness = QtWidgets.QLineEdit(self.gb_materialProperty)
        self.thickness.setObjectName("thickness")
        self.gridLayout_12.addWidget(self.thickness, 1, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_materialProperty, 0, 0, 2, 1)
        self.lab_image = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_image.sizePolicy().hasHeightForWidth())
        self.lab_image.setSizePolicy(sizePolicy)
        self.lab_image.setMinimumSize(QtCore.QSize(364, 264))
        self.lab_image.setMaximumSize(QtCore.QSize(364, 264))
        self.lab_image.setText("")
        self.lab_image.setPixmap(QtGui.QPixmap(":/image/image/201511240842560.jpg"))
        self.lab_image.setScaledContents(True)
        self.lab_image.setObjectName("lab_image")
        self.gridLayout_13.addWidget(self.lab_image, 1, 3, 1, 3)
        self.btn_inference = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_inference.sizePolicy().hasHeightForWidth())
        self.btn_inference.setSizePolicy(sizePolicy)
        self.btn_inference.setObjectName("btn_inference")
        self.gridLayout_13.addWidget(self.btn_inference, 2, 1, 1, 1)
        self.textEdit_inference = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_inference.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_inference.sizePolicy().hasHeightForWidth())
        self.textEdit_inference.setSizePolicy(sizePolicy)
        self.textEdit_inference.setReadOnly(True)
        self.textEdit_inference.setObjectName("textEdit_inference")
        self.gridLayout_13.addWidget(self.textEdit_inference, 3, 0, 1, 7)
        self.cbb_part = QtWidgets.QComboBox(self.tab_3)
        self.cbb_part.setObjectName("cbb_part")
        self.cbb_part.addItem("")
        self.cbb_part.addItem("")
        self.cbb_part.addItem("")
        self.cbb_part.addItem("")
        self.gridLayout_13.addWidget(self.cbb_part, 0, 4, 1, 2)
        self.lab_part = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_part.sizePolicy().hasHeightForWidth())
        self.lab_part.setSizePolicy(sizePolicy)
        self.lab_part.setObjectName("lab_part")
        self.gridLayout_13.addWidget(self.lab_part, 0, 3, 1, 1)
        self.btn_case_search = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_case_search.sizePolicy().hasHeightForWidth())
        self.btn_case_search.setSizePolicy(sizePolicy)
        self.btn_case_search.setObjectName("btn_case_search")
        self.gridLayout_13.addWidget(self.btn_case_search, 2, 0, 1, 1)
        self.gb_structureFeature = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_structureFeature.sizePolicy().hasHeightForWidth())
        self.gb_structureFeature.setSizePolicy(sizePolicy)
        self.gb_structureFeature.setObjectName("gb_structureFeature")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gb_structureFeature)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lab_angle2 = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_angle2.setObjectName("lab_angle2")
        self.gridLayout_16.addWidget(self.lab_angle2, 6, 0, 1, 1)
        self.angle2 = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.angle2.setObjectName("angle2")
        self.gridLayout_16.addWidget(self.angle2, 6, 1, 1, 1)
        self.angle4 = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.angle4.setObjectName("angle4")
        self.gridLayout_16.addWidget(self.angle4, 7, 1, 1, 1)
        self.line3 = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.line3.setObjectName("line3")
        self.gridLayout_16.addWidget(self.line3, 5, 1, 1, 1)
        self.lab_line3 = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_line3.setObjectName("lab_line3")
        self.gridLayout_16.addWidget(self.lab_line3, 5, 0, 1, 1)
        self.ASR = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.ASR.setObjectName("ASR")
        self.gridLayout_16.addWidget(self.ASR, 1, 1, 1, 1)
        self.lab_ASR = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_ASR.setObjectName("lab_ASR")
        self.gridLayout_16.addWidget(self.lab_ASR, 1, 0, 1, 1)
        self.lab_radius = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_radius.setObjectName("lab_radius")
        self.gridLayout_16.addWidget(self.lab_radius, 2, 0, 1, 1)
        self.length = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.length.setObjectName("length")
        self.gridLayout_16.addWidget(self.length, 0, 1, 1, 1)
        self.lab_line1 = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_line1.setObjectName("lab_line1")
        self.gridLayout_16.addWidget(self.lab_line1, 3, 0, 1, 1)
        self.line1 = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.line1.setObjectName("line1")
        self.gridLayout_16.addWidget(self.line1, 3, 1, 1, 1)
        self.radius = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.radius.setObjectName("radius")
        self.gridLayout_16.addWidget(self.radius, 2, 1, 1, 1)
        self.lab_length = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_length.setObjectName("lab_length")
        self.gridLayout_16.addWidget(self.lab_length, 0, 0, 1, 1)
        self.lab_angle4 = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_angle4.setObjectName("lab_angle4")
        self.gridLayout_16.addWidget(self.lab_angle4, 7, 0, 1, 1)
        self.lab_springback = QtWidgets.QLabel(self.gb_structureFeature)
        self.lab_springback.setObjectName("lab_springback")
        self.gridLayout_16.addWidget(self.lab_springback, 8, 0, 1, 1)
        self.springback = QtWidgets.QLineEdit(self.gb_structureFeature)
        self.springback.setObjectName("springback")
        self.gridLayout_16.addWidget(self.springback, 8, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_structureFeature, 0, 2, 2, 1)
        self.btn_weight = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_weight.sizePolicy().hasHeightForWidth())
        self.btn_weight.setSizePolicy(sizePolicy)
        self.btn_weight.setObjectName("btn_weight")
        self.gridLayout_13.addWidget(self.btn_weight, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menutable = QtWidgets.QMenu(self.menu_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-data-sheet-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menutable.setIcon(icon3)
        self.menutable.setObjectName("menutable")
        self.menuinsert = QtWidgets.QMenu(self.menutable)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-table-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuinsert.setIcon(icon4)
        self.menuinsert.setObjectName("menuinsert")
        self.menudelete = QtWidgets.QMenu(self.menutable)
        self.menudelete.setObjectName("menudelete")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.about = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-关于-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon5)
        self.about.setObjectName("about")
        self.actionnew = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-file-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew.setIcon(icon6)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setIcon(icon2)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-save-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon7)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-export-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexit.setIcon(icon8)
        self.actionexit.setObjectName("actionexit")
        self.editUndo = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-撤销-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndo.setIcon(icon9)
        self.editUndo.setObjectName("editUndo")
        self.editRecover = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-恢复-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRecover.setIcon(icon10)
        self.editRecover.setObjectName("editRecover")
        self.editCopy = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-copy-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCopy.setIcon(icon11)
        self.editCopy.setObjectName("editCopy")
        self.editPaste = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-paste-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPaste.setIcon(icon12)
        self.editPaste.setObjectName("editPaste")
        self.editCrop = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-cut-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCrop.setIcon(icon13)
        self.editCrop.setObjectName("editCrop")
        self.editDelete = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-删除-bin-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editDelete.setIcon(icon14)
        self.editDelete.setObjectName("editDelete")
        self.insertRow = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-add-row-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertRow.setIcon(icon15)
        self.insertRow.setObjectName("insertRow")
        self.insertCol = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-add-column-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertCol.setIcon(icon16)
        self.insertCol.setObjectName("insertCol")
        self.deleteRow = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-delete-row-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteRow.setIcon(icon17)
        self.deleteRow.setObjectName("deleteRow")
        self.deleteCol = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-delete-column-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteCol.setIcon(icon18)
        self.deleteCol.setObjectName("deleteCol")
        self.menu.addAction(self.actionnew)
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionexit)
        self.menuinsert.addAction(self.insertRow)
        self.menuinsert.addAction(self.insertCol)
        self.menudelete.addAction(self.deleteRow)
        self.menudelete.addAction(self.deleteCol)
        self.menutable.addAction(self.menuinsert.menuAction())
        self.menutable.addAction(self.menudelete.menuAction())
        self.menu_2.addAction(self.editUndo)
        self.menu_2.addAction(self.editRecover)
        self.menu_2.addAction(self.editCopy)
        self.menu_2.addAction(self.editPaste)
        self.menu_2.addAction(self.editCrop)
        self.menu_2.addAction(self.editDelete)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menutable.menuAction())
        self.menu_4.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionnew)
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.insertRow)
        self.toolBar.addAction(self.insertCol)
        self.toolBar.addAction(self.deleteRow)
        self.toolBar.addAction(self.deleteCol)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editDelete)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cbb_aFunc_output.setCurrentIndex(4)
        self.cbb_optimizer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.userName)
        MainWindow.setTabOrder(self.userName, self.password)
        MainWindow.setTabOrder(self.password, self.btn_login)
        MainWindow.setTabOrder(self.btn_login, self.btn_exit)
        MainWindow.setTabOrder(self.btn_exit, self.cbb_database)
        MainWindow.setTabOrder(self.cbb_database, self.filePath)
        MainWindow.setTabOrder(self.filePath, self.lineEdit_search)
        MainWindow.setTabOrder(self.lineEdit_search, self.btn_execute)
        MainWindow.setTabOrder(self.btn_execute, self.table_data)
        MainWindow.setTabOrder(self.table_data, self.textEdit_database)
        MainWindow.setTabOrder(self.textEdit_database, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.data_path)
        MainWindow.setTabOrder(self.data_path, self.btn_load_data)
        MainWindow.setTabOrder(self.btn_load_data, self.inputLayer)
        MainWindow.setTabOrder(self.inputLayer, self.hideLayer_0)
        MainWindow.setTabOrder(self.hideLayer_0, self.cbb_aFunc_0)
        MainWindow.setTabOrder(self.cbb_aFunc_0, self.cbb_aFunc_output)
        MainWindow.setTabOrder(self.cbb_aFunc_output, self.learningRate)
        MainWindow.setTabOrder(self.learningRate, self.cbb_optimizer)
        MainWindow.setTabOrder(self.cbb_optimizer, self.cbb_lossFunc)
        MainWindow.setTabOrder(self.cbb_lossFunc, self.trainEpoch)
        MainWindow.setTabOrder(self.trainEpoch, self.dropout)
        MainWindow.setTabOrder(self.dropout, self.dsb_testRate)
        MainWindow.setTabOrder(self.dsb_testRate, self.checkBox_saveModel)
        MainWindow.setTabOrder(self.checkBox_saveModel, self.checkBox_saveImg)
        MainWindow.setTabOrder(self.checkBox_saveImg, self.btn_suspend)
        MainWindow.setTabOrder(self.btn_suspend, self.btn_startTrain)
        MainWindow.setTabOrder(self.btn_startTrain, self.textEdit_trainResult)
        MainWindow.setTabOrder(self.textEdit_trainResult, self.PH)
        MainWindow.setTabOrder(self.PH, self.thickness)
        MainWindow.setTabOrder(self.thickness, self.elongation)
        MainWindow.setTabOrder(self.elongation, self.nValue)
        MainWindow.setTabOrder(self.nValue, self.rValue)
        MainWindow.setTabOrder(self.rValue, self.tensile_strength)
        MainWindow.setTabOrder(self.tensile_strength, self.yield_strength)
        MainWindow.setTabOrder(self.yield_strength, self.velocity)
        MainWindow.setTabOrder(self.velocity, self.pressure)
        MainWindow.setTabOrder(self.pressure, self.friction)
        MainWindow.setTabOrder(self.friction, self.gap)
        MainWindow.setTabOrder(self.gap, self.drawBead)
        MainWindow.setTabOrder(self.drawBead, self.length)
        MainWindow.setTabOrder(self.length, self.ASR)
        MainWindow.setTabOrder(self.ASR, self.radius)
        MainWindow.setTabOrder(self.radius, self.line1)
        MainWindow.setTabOrder(self.line1, self.line3)
        MainWindow.setTabOrder(self.line3, self.angle2)
        MainWindow.setTabOrder(self.angle2, self.angle4)
        MainWindow.setTabOrder(self.angle4, self.springback)
        MainWindow.setTabOrder(self.springback, self.cbb_part)
        MainWindow.setTabOrder(self.cbb_part, self.btn_case_search)
        MainWindow.setTabOrder(self.btn_case_search, self.btn_inference)
        MainWindow.setTabOrder(self.btn_inference, self.textEdit_inference)
        MainWindow.setTabOrder(self.textEdit_inference, self.comboBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "汽车冲压件智能CAPP系统"))
        self.lab_password.setText(_translate("MainWindow", "密  码："))
        self.btn_exit.setText(_translate("MainWindow", "退出"))
        self.lab_password_2.setText(_translate("MainWindow", "文  档："))
        self.lab_user.setText(_translate("MainWindow", "用户名："))
        self.textEdit_database.setPlaceholderText(_translate("MainWindow", "output:"))
        self.password.setText(_translate("MainWindow", "123456"))
        self.btn_login.setText(_translate("MainWindow", "登录"))
        self.lab_database.setText(_translate("MainWindow", "数据库："))
        self.cbb_database.setCurrentText(_translate("MainWindow", "请选择数据库"))
        self.cbb_database.setItemText(0, _translate("MainWindow", "请选择数据库"))
        self.cbb_database.setItemText(1, _translate("MainWindow", "material"))
        self.cbb_database.setItemText(2, _translate("MainWindow", "structure"))
        self.cbb_database.setItemText(3, _translate("MainWindow", "technology"))
        self.cbb_database.setItemText(4, _translate("MainWindow", "part_library"))
        self.userName.setText(_translate("MainWindow", "root"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "请输入mysql命令..."))
        self.btn_execute.setText(_translate("MainWindow", "执行"))
        self.btn_open.setText(_translate("MainWindow", "浏览..."))
        self.btn_upload.setText(_translate("MainWindow", "上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "数据管理"))
        self.lab_Epoch.setText(_translate("MainWindow", "Epoch:"))
        self.learningRate.setText(_translate("MainWindow", "0.01"))
        self.lab_input.setText(_translate("MainWindow", "输入层："))
        self.lab_optimizer.setText(_translate("MainWindow", "优化器："))
        self.cbb_aFunc_output.setItemText(0, _translate("MainWindow", "sigmoid"))
        self.cbb_aFunc_output.setItemText(1, _translate("MainWindow", "relu"))
        self.cbb_aFunc_output.setItemText(2, _translate("MainWindow", "tanh"))
        self.cbb_aFunc_output.setItemText(3, _translate("MainWindow", "softmax"))
        self.cbb_aFunc_output.setItemText(4, _translate("MainWindow", "None"))
        self.lab_learningRate.setText(_translate("MainWindow", "学习率："))
        self.lab_lossFunc.setText(_translate("MainWindow", "评价指标："))
        self.dropout.setText(_translate("MainWindow", "1"))
        self.cbb_optimizer.setItemText(0, _translate("MainWindow", "AdamOptimizer"))
        self.cbb_optimizer.setItemText(1, _translate("MainWindow", "AdagradOptimizer"))
        self.cbb_optimizer.setItemText(2, _translate("MainWindow", "AdagradDAOptimizer"))
        self.cbb_optimizer.setItemText(3, _translate("MainWindow", "FtrlOptimizer"))
        self.cbb_optimizer.setItemText(4, _translate("MainWindow", "GradientDescentOptimizer"))
        self.cbb_optimizer.setItemText(5, _translate("MainWindow", "MomentumOptimizer"))
        self.cbb_optimizer.setItemText(6, _translate("MainWindow", "ProximalAdagradOptimizer"))
        self.cbb_optimizer.setItemText(7, _translate("MainWindow", "ProximalGradientDescentOptimizer"))
        self.cbb_optimizer.setItemText(8, _translate("MainWindow", "RMSPropOptimizer"))
        self.lab_trainEpoch.setText(_translate("MainWindow", "训练周期："))
        self.lab_dropout.setText(_translate("MainWindow", "Dropout："))
        self.checkBox_saveModel.setText(_translate("MainWindow", "保存模型"))
        self.checkBox_saveImg.setText(_translate("MainWindow", "保存图片"))
        self.lab_dropout_2.setText(_translate("MainWindow", "test rate："))
        self.trainEpoch.setText(_translate("MainWindow", "1000"))
        self.cbb_lossFunc.setItemText(0, _translate("MainWindow", "MSE"))
        self.cbb_lossFunc.setItemText(1, _translate("MainWindow", "RMSE"))
        self.cbb_lossFunc.setItemText(2, _translate("MainWindow", "MAE"))
        self.cbb_lossFunc.setItemText(3, _translate("MainWindow", "R-squared"))
        self.lab_hide.setText(_translate("MainWindow", "隐藏层："))
        self.data_path.setPlaceholderText(_translate("MainWindow", "读取本地数据..."))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "请选择数据库"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "material"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "structure"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "technology"))
        self.w_b_path.setPlaceholderText(_translate("MainWindow", "读取权值/偏置..."))
        self.lab_LossStep.setText(_translate("MainWindow", "显示步长："))
        self.outputLayer.setText(_translate("MainWindow", "1"))
        self.cbb_aFunc_0.setItemText(0, _translate("MainWindow", "sigmoid"))
        self.cbb_aFunc_0.setItemText(1, _translate("MainWindow", "relu"))
        self.cbb_aFunc_0.setItemText(2, _translate("MainWindow", "tanh"))
        self.cbb_aFunc_0.setItemText(3, _translate("MainWindow", "softmax"))
        self.cbb_aFunc_0.setItemText(4, _translate("MainWindow", "None"))
        self.lab_output.setText(_translate("MainWindow", "输出层："))
        self.hideLayer_0.setText(_translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "智能学习"))
        self.gb_processPeremeter.setTitle(_translate("MainWindow", "工艺参数"))
        self.lab_friction.setText(_translate("MainWindow", "摩擦系数："))
        self.lab_drawBead.setText(_translate("MainWindow", "拉延筋："))
        self.lab_velocity.setText(_translate("MainWindow", "冲压速度："))
        self.lab_gap.setText(_translate("MainWindow", "模具间隙："))
        self.lab_pressure.setText(_translate("MainWindow", "压边力："))
        self.gb_materialProperty.setTitle(_translate("MainWindow", "材料属性"))
        self.lab_tensile.setText(_translate("MainWindow", "抗拉强度："))
        self.lab_yield.setText(_translate("MainWindow", "屈服强度："))
        self.lab_n.setText(_translate("MainWindow", "n值："))
        self.lab_PH.setText(_translate("MainWindow", "牌号："))
        self.lab_elongation.setText(_translate("MainWindow", "延伸率："))
        self.lab_r.setText(_translate("MainWindow", "r值："))
        self.lab_thickness.setText(_translate("MainWindow", "厚度："))
        self.btn_inference.setText(_translate("MainWindow", "推理分析"))
        self.cbb_part.setItemText(0, _translate("MainWindow", "B柱"))
        self.cbb_part.setItemText(1, _translate("MainWindow", "A柱"))
        self.cbb_part.setItemText(2, _translate("MainWindow", "左车门内板"))
        self.cbb_part.setItemText(3, _translate("MainWindow", "右车门内板"))
        self.lab_part.setText(_translate("MainWindow", "零件类型："))
        self.btn_case_search.setText(_translate("MainWindow", "案例检索"))
        self.gb_structureFeature.setTitle(_translate("MainWindow", "结构特征"))
        self.lab_angle2.setText(_translate("MainWindow", "圆角2："))
        self.lab_line3.setText(_translate("MainWindow", "直线3："))
        self.lab_ASR.setText(_translate("MainWindow", "弧直比："))
        self.lab_radius.setText(_translate("MainWindow", "半径："))
        self.lab_line1.setText(_translate("MainWindow", "直线1："))
        self.lab_length.setText(_translate("MainWindow", "总长："))
        self.lab_angle4.setText(_translate("MainWindow", "圆角4："))
        self.lab_springback.setText(_translate("MainWindow", "回弹："))
        self.btn_weight.setText(_translate("MainWindow", "特征权重"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "专家推理"))
        self.groupBox_5.setTitle(_translate("MainWindow", "事实采集"))
        self.comboBox.setItemText(0, _translate("MainWindow", "理论知识库"))
        self.comboBox.setItemText(1, _translate("MainWindow", "经验案例库"))
        self.groupBox_4.setTitle(_translate("MainWindow", "规则采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "知识采集"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menutable.setTitle(_translate("MainWindow", "table"))
        self.menuinsert.setTitle(_translate("MainWindow", "insert"))
        self.menudelete.setTitle(_translate("MainWindow", "delete"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.about.setText(_translate("MainWindow", "about"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.editUndo.setText(_translate("MainWindow", "undo"))
        self.editRecover.setText(_translate("MainWindow", "recover"))
        self.editCopy.setText(_translate("MainWindow", "copy"))
        self.editPaste.setText(_translate("MainWindow", "paste"))
        self.editCrop.setText(_translate("MainWindow", "crop"))
        self.editDelete.setText(_translate("MainWindow", "delete"))
        self.insertRow.setText(_translate("MainWindow", "row"))
        self.insertCol.setText(_translate("MainWindow", "col"))
        self.deleteRow.setText(_translate("MainWindow", "row"))
        self.deleteCol.setText(_translate("MainWindow", "col"))

import resources_rc
